runtime: python38

handlers:
- url: /
  script: web_app.py

- url: /dataviewer
  script: web_app.py

- url: /about
  script: web_app.py

- url: /.*
  script: web_app.py

- url: /stylesheet
  static_dir: static/css/main.css

- url: /(.*\.tff)$
  static_files: static/css/\1
  upload: static/css/.*\.(gif|png|jpg)$

- url: /(.*\.ico)$
  static_files: static//\1
  upload: static/.*\.(gif|png|jpg)$
