runtime: python38

instance_class: F4_1G

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'true'

resources:
  cpu: 4
  memory_gb: 4
  disk_size_gb: 10

handlers:
- url: /static/*
  static_dir: static
  secure: always
- url: /*
  secure: always
  script: auto